services:
    web:
        build:  .
        environment:
            - BYPASS_AUTHORIZATION=true
            - REDIS_HOST=redis
            - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
            - WHISPER_LANGUAGE=${WHISPER_LANGUAGE:-es}
            - ENABLED_MODULES=${ENABLED_MODULES:-streaming_whisper}
        platform: linux/amd64
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8003:8003"
    redis:
        image: "redis:alpine"
        platform: linux/amd64
