services:
    skynet:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
            - WHISPER_LANGUAGE=${WHISPER_LANGUAGE:-es}
            - ENABLED_MODULES=streaming_whisper
            - BYPASS_AUTHORIZATION=true
        ports:
            - "8001:8001"
        depends_on:
            - redis
    redis:
        image: redis:7.2.4
        ports:
            - "6379:6379"
