services:
    web:
        build:  .
        environment:
            - BYPASS_AUTHORIZATION=true
            - REDIS_HOST=redis
            - FIREWORKS_API_KEY=${FIREWORKS_API_KEY}
            - WHISPER_LANGUAGE=${WHISPER_LANGUAGE:-es}
            - ENABLED_MODULES=${ENABLED_MODULES:-streaming_whisper}
        platform: linux/amd64
        ports:
            - "8000:8000"
        depends_on:
            - redis
    redis:
        image: redis:7.2.4
        ports:
            - "6379:6379"
