[tool.poetry]
name = "skynet"
version = "0.1.0"
description = ""
authors = ["Jitsi Team <team@jitsi.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.96.0"
uvicorn = "^0.22.0"
langchain = "^0.0.194"
pydantic = "^1.10.9"
openai = "^0.27.8"
tiktoken = "^0.4.0"
fastapi-versionizer = "^0.1.6"
pyjwt = "2.6.0"
cryptography = "^41.0.1"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
